@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
package Model.Events {
  enum GameEventType {
    + INIT_GAME
    + REFRESH_ALL
    + GAME_OVER_WIN
    + GAME_OVER_LOSE
    + WEAPON_FIRED
    + TURN_ENDED_PLAYER
    + TORNADO_EFFECT
    + TORNADO_HIT
    + BLACK_HOLE_TRIGGER
    + BLACK_HOLE_BACKFIRE
    + BLACK_HOLE_ABSORBED
    + ITEM_BOMB_FOUND
    + ITEM_SONAR_FOUND
  }

  class GameEvent <<record>> {
    + GameEvent(type: GameEventType)
    + GameEvent(type: GameEventType, coords: Coordinates)
    + GameEvent(type: GameEventType, result: WeaponResult)
    + GameEvent(type: GameEventType, coords: Coordinates, weaponResult: WeaponResult)
    + type(): GameEventType
    + coords(): Coordinates
    + weaponResult(): WeaponResult
  }
}
@enduml

